[AudioEngine]
uMaxNumPaths=255
uCommandQueueSize=262144
bEnableGameSyncPreparation=false
uContinuousPlaybackLookAhead=1
uNumSamplesPerFrame=512
uMonitorQueuePoolSize=1048576
uCpuMonitorQueueMaxSize=262144
uMaxHardwareTimeoutMs=1000
bUseSoundBankMgrThread=false
bUseLEngineThread=false
szPluginDLLPath=plugins/wwise
# ZX(Default), XY, XZ or YZ
eFloorPlane=ZX
fGameUnitsToMeters=1.0
uBankReadBufferSize=262144
fDebugOutOfRangeLimit=16.0
bDebugOutOfRangeCheckEnabled=false
bOfflineRendering=false

[OutputSettings]
audioDeviceShareset=
idDevice=0
ePanningRule=Speakers
uNumChannels=0
eConfigType=Anonymous
uChannelMask=0

[DeviceSettings]
uIOMemorySize=2097152
uIOMemoryAlignment=32
uGranularity=32768
fTargetAutoStmBufferLength=380.f
uMaxConcurrentIO=8
bUseStreamCache=false
# (uint32)-1 == UINT32_MAX (No Restriction)
uMaxCachePinnedBytes=-1

[Platform]
uSampleRate=48000
uMaxSystemAudioObjects=128

[SpatialAudio]
uMaxSoundPropagationDepth=8
fMovementThreshold=0.25
uNumberOfPrimaryRays=35
uMaxReflectionOrder=2
uMaxDiffractionOrder=4
uMaxDiffractionPaths=8
uMaxGlobalReflectionPaths=0
uMaxEmitterRoomAuxSends=3
uDiffractionOnReflectionsOrder=2
fMaxDiffractionAngleDegrees=180.0
fMaxPathLength=1000.0
fCPULimitPercentage=0.0
fSmoothingConstantMs=0.0
uLoadBalancingSpread=1.0
bEnableGeometricDiffractionAndTransmission=true
bCalcEmitterVirtualPosition=true
# Max, Add or Multiply
eTransmissionOperation=Max
